; A file containing the morse code alphabet (excluding numbers) 
; that has been converted into hexadecimal
; They have been reversed as we represent the letter backwards in r27

;counter = 1
M_E = 0x00 ; 0 .
M_T = 0x01 ; 1 -

;counter = 2
M_A = 0x02 ; (10) 01 .-
M_I = 0x00 ; 00 ..
M_N = 0x01 ; (01) 10 -.
M_M = 0x03 ; 11 --

;counter = 3
M_D = 0x01 ; (001) 100 -..
M_G = 0x03 ; (011) 110 --.
M_K = 0x05 ; 101 -.-
M_O = 0x07 ; 111 ---
M_R = 0x02 ; 010 .-.
M_S = 0x00 ; 000 ...
M_U = 0x04 ; (100) 001 ..-
M_W = 0x06 ; (110) 011 .--

;counter = 4
M_B = 0x01 ; (0001) 1000 -...
M_C = 0x05 ; (0101) 1010 -.-.
M_F = 0x04 ; (0100) 0010 ..-.
M_H = 0x00 ; 0000 ....
M_J = 0x0E ; (1110) 0111 .---
M_L = 0x02 ; (0010) 0100 .-..
M_P = 0x06 ; 0110 .--.
M_Q = 0x0B ; (1011) 1101 --.-
M_V = 0x08 ; (1000) 0001 ...-
M_X = 0x09 ; 1001 -..-
M_Y = 0x0D ; (1101) 1011 -.--
M_Z = 0x03 ; (0011) 1100 --..